### ISSUE TITLE
Failed to execute 'atob'

### ISSUE THREAD

**Issue by harshcut** [harshcut/base64#1]
## Description

Throw `AlertDialog` for `DOMException` when decode operation fails to execute due to invalid input string. Full error log below.

## AlertDialog

Alert Dialogs are a specific type of Dialog. They display important information that users need to acknowledge. More information can be found at [react-spectrum](https://react-spectrum.adobe.com/react-spectrum/AlertDialog.html) documentation.

## Fix

The Decode Button will be have to changed as the user types to make code available for `AlertDialog`. By creating a new `hasError` state might help. Additionally a `throwAlertDialog` method will be used to change state.

```javascript
throwAlertDialog = () => {
  try {
    atob(this.defaultStringField.current.getInputElement().value);
  } catch (error) {
    this.setState({ hasError: true });
    return;
  }
  this.setState({ hasError: false });
}
```

## Log

```javascript
DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at App.throwAlertDialog (http://localhost:3000/base64/static/js/main.chunk.js:79:9)
    at onChange (http://localhost:3000/base64/static/js/1.chunk.js:8050:22)
    at HTMLUnknownElement.callCallback (http://localhost:3000/base64/static/js/1.chunk.js:32402:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/base64/static/js/1.chunk.js:32451:20)
    at invokeGuardedCallback (http://localhost:3000/base64/static/js/1.chunk.js:32504:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/base64/static/js/1.chunk.js:32519:29)
    at executeDispatch (http://localhost:3000/base64/static/js/1.chunk.js:32604:7)
    at executeDispatchesInOrder (http://localhost:3000/base64/static/js/1.chunk.js:32629:9)
    at executeDispatchesAndRelease (http://localhost:3000/base64/static/js/1.chunk.js:35513:9)
    at executeDispatchesAndReleaseTopLevel (http://localhost:3000/base64/static/js/1.chunk.js:35522:14)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (http://localhost:3000/base64/static/js/1.chunk.js:35492:13)
    at runEventsInBatch (http://localhost:3000/base64/static/js/1.chunk.js:35539:7)
    at runExtractedPluginEventsInBatch (http://localhost:3000/base64/static/js/1.chunk.js:35749:7)
    at handleTopLevel (http://localhost:3000/base64/static/js/1.chunk.js:35793:9)
    at batchedEventUpdates$1 (http://localhost:3000/base64/static/js/1.chunk.js:53939:16)
    at batchedEventUpdates (http://localhost:3000/base64/static/js/1.chunk.js:33011:16)
    at dispatchEventForLegacyPluginEventSystem (http://localhost:3000/base64/static/js/1.chunk.js:35803:9)
    at attemptToDispatchEvent (http://localhost:3000/base64/static/js/1.chunk.js:36523:9)
    at dispatchEvent (http://localhost:3000/base64/static/js/1.chunk.js:36444:23)
    at unstable_runWithPriority (http://localhost:3000/base64/static/js/1.chunk.js:63065:16)
    at runWithPriority$1 (http://localhost:3000/base64/static/js/1.chunk.js:43289:14)
    at discreteUpdates$1 (http://localhost:3000/base64/static/js/1.chunk.js:53956:16)
    at discreteUpdates (http://localhost:3000/base64/static/js/1.chunk.js:33024:16)
    at dispatchDiscreteEvent (http://localhost:3000/base64/static/js/1.chunk.js:36423:7)
```

**Comment by harshcut** [comment]
## Task Completed

Ending Thread for **Failed to execute 'atob'**. If any issue arises, the issue can be opened.

## Commit History

- [x] update for `master` branch b81e020c1eba89c61fc7dae2bc18d8719fa99d2f
- [x] update for `gh-pages` build d2458b052e065cddc0016c3305aabe5ff131162b
